# Generated by Django 3.2.7 on 2021-09-06 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=70)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='relationships.appuser')),
                ('aadhaar_no', models.CharField(max_length=12, unique=True)),
                ('mobile_no', models.IntegerField()),
                ('updated_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
