# Generated by Django 3.2.7 on 2021-09-06 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='employee',
            new_name='appuser',
        ),
    ]
