# Generated by Django 3.2.7 on 2021-09-06 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0002_rename_employee_userdetails_appuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relationships.userdetails')),
                ('likes', models.IntegerField()),
            ],
            bases=('relationships.userdetails',),
        ),
    ]
